const recipesData: Array<Record<string, any>> = [
  {
    id: 1,
    rating: 4.6,
    reviewCount: 98,
    cuisine: "Italian",
    name: "Classic Margherita Pizza",
    image: "https://cdn.dummyjson.com/recipe-images/1.webp",
  },
  {
    id: 2,
    rating: 4.7,
    reviewCount: 26,
    cuisine: "Asian",
    name: "Vegetarian Stir-Fry",
    image: "https://cdn.dummyjson.com/recipe-images/2.webp",
  },
  {
    id: 3,
    rating: 4.9,
    reviewCount: 13,
    cuisine: "American",
    name: "Chocolate Chip Cookies",
    image: "https://cdn.dummyjson.com/recipe-images/3.webp",
  },
  {
    id: 4,
    rating: 4.9,
    reviewCount: 82,
    cuisine: "Italian",
    name: "Chicken Alfredo Pasta",
    image: "https://cdn.dummyjson.com/recipe-images/4.webp",
  },
  {
    id: 5,
    rating: 4.9,
    reviewCount: 63,
    cuisine: "Mexican",
    name: "Mango Salsa Chicken",
    image: "https://cdn.dummyjson.com/recipe-images/5.webp",
  },
  {
    id: 6,
    rating: 4.4,
    reviewCount: 59,
    cuisine: "Mediterranean",
    name: "Quinoa Salad with Avocado",
    image: "https://cdn.dummyjson.com/recipe-images/6.webp",
  },
  {
    id: 7,
    rating: 4.7,
    reviewCount: 95,
    cuisine: "Italian",
    name: "Tomato Basil Bruschetta",
    image: "https://cdn.dummyjson.com/recipe-images/7.webp",
  },
  {
    id: 8,
    rating: 4.7,
    reviewCount: 58,
    cuisine: "Asian",
    name: "Beef and Broccoli Stir-Fry",
    image: "https://cdn.dummyjson.com/recipe-images/8.webp",
  },
  {
    id: 9,
    rating: 4.6,
    reviewCount: 82,
    cuisine: "Italian",
    name: "Caprese Salad",
    image: "https://cdn.dummyjson.com/recipe-images/9.webp",
  },
  {
    id: 10,
    rating: 4.3,
    reviewCount: 5,
    cuisine: "Italian",
    name: "Shrimp Scampi Pasta",
    image: "https://cdn.dummyjson.com/recipe-images/10.webp",
  },
];

export default recipesData;